[package]
name = "corpus-prep-tools"
version = "0.1.0"
authors = ["Daniël de Kok <me@danieldk.eu>"]
edition = "2018"

[dependencies]
clap = "2.31"
conllx = "0.11"
flate2 = "1"
lazy_static = "1"
regex = "1"
siphasher = "0.2"
stdinout = "0.4"
